### ISSUE TITLE
WindowsEvent label

### ISSUE THREAD

**Issue by nedaAF** [logpai/loghub#10]
I need to mining through windows events to capture the events from them.
Unfortunately, your windows events are without a label.
Do you have any metadata about them? 
 Or doe you know any paper used these events and preparing the labels or metadata?

Thanks

**Comment by jakezachariahnixon** [comment]
An up-to-date list of papers which have used and cited this dataset is in the readme of the repo. 

Alternatively, there is a list here on Google Scholar: 
https://scholar.google.com/scholar?cites=1394542423353254953&as_sdt=2005&sciodt=0,5&hl=en

I had a quick look over the list for you and, unfortunately, I don't believe that anyone has labelled this data.

**Comment by jimzhu** [comment]
Yes, labelled data is really scarce. This is the main motivation for this project to share the data we have. Logs open here are for not only anomaly detection, but for log parsing, log compression, log streaming (no label needed). We have indicated whether the data is **labeled** in the README table.
