### ISSUE TITLE
HDFS log entry count differ between loghub and Deeplog paper

### ISSUE THREAD

**Issue by juwikuang** [logpai/loghub#11]
in Loghub, HDFS1 has 11,175,629 entries.
in Deeplog, the number is 11,197,954 logs.
I am confused. 

thanks

**Comment by jimzhu** [comment]
Sorry for late replay. Our data did not come from Deeplog's paper. We use the same set with our ISSRE paper.

**Comment by mooks42** [comment]
Hi, it would be really great if you could change the readme of your HDFS logs.
If looks like HDFS_1 is the same Dataset as used in [Detecting Large-Scale System Problems by Mining Console Logs](https://people.eecs.berkeley.edu/~jordan/papers/xu-etal-sosp09.pdf), however the total amount of lines and anomalys is not the same. Therefore, all my work using HDFS_1 and referencing to this publication is wrong :/
