### ISSUE TITLE
What is the reference to choose CBS logs as the dataset

### ISSUE THREAD

**Issue by Wapiti08** [logpai/loghub#12]
I have made some research about how to check the event logs to do digital forensic. I found the security logs have the largest relationship with hacker attacks.
When a unauthenticated access or login happen, you can find the record on security logs. While there is nothing showed in CBS logs.

So I have the doubt whether such kind of dataset is really useful when doing the anomaly detection.

**Comment by jimzhu** [comment]
We choose CBS logs since the size is large enough. The data were generated by a peronal computer, not a server. So security issues may not happen at all. We have used the logs only for log parsing research before.

**Comment by Wapiti08** [comment]
Thanks for your reply. I did some research about the IR(incidents response). Basically, the attacks will be found through the analysis of system/ security/ applications. The security one the main source for tracking attacks. So I would like to share this information. Cuz I am in SOC team. Thank you so much!


| |
tzrzhuoran
邮箱：tzrzhuoran@163.com
|

Signature is customized by Netease Mail Master

On 12/26/2019 23:16, Jamie Zhu wrote:

We choose CBS logs since the size is large enough. The data were generated by a peronal computer, not a server. So security issues may not happen at all. We have used the logs only for log parsing research before.
