### ISSUE TITLE
OpenStack Logs

### ISSUE THREAD

**Issue by wildfire8966** [logpai/loghub#16]
你好何教授，

我想最近在做日志相关的探索，想详细了解下OpenStack数据集里的日志每个文件是做什么的？

openstack_abnormal 这个文件里的instance全部是异常的吗？

openstack_normal1 和 openstack_normal2 两个日志有什么区别吗？

labels 文件里为什么只有4个注入异常类的instance， openstack_abnormal 里的instance数远超4个，那么其他的instance是什么异常呢？这4个标出来的instance有什么特殊吗？

多谢！

**Comment by zhujiem** [comment]
For the usage of this dataset, please refer to an example: https://github.com/nailo2c/deeplog/blob/master/example/preprocess.py
