### ISSUE TITLE
Loghub Dataset 503 Service Unavailable

### ISSUE THREAD

**Issue by Xpitfire** [logpai/loghub#19]
Hi. 

I tried to download the dataset from https://zenodo.org/record/3227177 but could not download any file. 
After clicking and waiting for a while, I receive a 503 Service Unavailable error. 

Could you please verify if the data is still publically available.

Thank you in advance.
Best,
Marius

**Comment by JinYang88** [comment]
It seems normal from our side, could you please try again maybe in another network environment?
