### ISSUE TITLE
Can I redistribute some of the 2K sample logs?

### ISSUE THREAD

**Issue by donghwan-shin** [logpai/loghub#21]
Dear LogPai team,

Thank you for maintaining this wonderful log datasets.

I just wonder if it’s okay to redistribute a few of your 2K logs (e.g., https://github.com/logpai/loghub/blob/master/HDFS/HDFS_2k.log) just as an example log dataset in my replication package. 

Though you kindly noted [here](https://github.com/logpai/loghub#license) that “the log datasets are freely available for research purposes”, it’s not clear to me if this includes the *redistribution* right of the log datasets. If possible, I will present a clear reference to this dataset repository and then include a few sample logs in my replication package as examples. 

Looking forward to hearing from you soon.

Thanks,
Donghwan

**Comment by PinjiaHe** [comment]
Dear Donghwan,

Sure, feel free to redistribute the logs, and thank you for using LogPAI!

Best,
Pinjia

**Comment by donghwan-shin** [comment]
Thank you, Pinjia!

**Comment by zhujiem** [comment]
> Thank you so much, Pinjia!

Please remember to retrain the source of datasets. thanks!
