### ISSUE TITLE
Multi-class resources availability

### ISSUE THREAD

**Issue by wailoktam** [logpai/loghub#25]
There are some companies like [Zebrium](https://www.zebrium.com/) around saying that they get an AI to do root cause analysis of logs. I think root cause analysis is not just about splitting the data between normal and abnormal. But I can only find binary classification data. Is there any multi-class data?

**Comment by JinYang88** [comment]
Thanks for letting us know about the exciting project Zebrium. Unfortunately, we did not include multi-class data in this repo.
