### ISSUE TITLE
Make data available via Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [logpai/loghub#35]
Very cool dataset and impressive to see how much use/impact it is having! It would be nice if it was also possible to access it via the Hugging Face Hub (https://huggingface.co/datasets).  There are a few possible approaches to doing this (and it's also possible to have gated acces). Happy to help with this if it is of interest!

**Comment by zhujiem** [comment]
Thanks for your suggestion! Any additional benefits to host datasets on huggingface?

**Comment by davanstrien** [comment]
If you just shared the files via the Hub, there are a few main advantages: 
- Git-based, so can fit into workflows more easily 
- A nice [library](https://huggingface.co/docs/huggingface_hub/index to repos + files ) for programmatic uploading/downloading from the hub.
- local CDN for faster downloads 

If you organize the dataset in a structured way, i.e. by language, you can also make it easy for people to download everything/download a specific subset of languages. [The Stack](https://huggingface.co/datasets/bigcode/the-stack) dataset is a good example of this for a code dataset where you can either download everything or download only a particular language(s). Another way to achieve this would be via a [dataset loading script](https://huggingface.co/docs/datasets/dataset_script). 

A dataset loading script would give users even more control for what/how to download data. This requires a bit more work upfront but can be a nice way of avoiding users of the dataset reimplementing similar download scripts multiple times.

**Comment by zhujiem** [comment]
Cool! If you are interested in help with this task, please go ahead. But please keep the README and LICENSE files.
