### ISSUE TITLE
Anomaly Items in Dataset?

### ISSUE THREAD

**Issue by Wapiti08** [logpai/loghub#36]
Hi,

Can I ask whether there is any other dataset including clear abnormal items inside logs except HDFS? Thanks.

I notice BGl is labelled dataset. But I did not find the clear labels regarding it from the [hub](https://zenodo.org/record/3227177).

Please let me know more details.

Thanks

**Comment by Sun-HR02** [comment]
Hey, I have the same question. Could you give me a helping hand?

**Comment by Wapiti08** [comment]
> Hey, I have the same question. Could you give me a helping hand?

"-" indicates non-alert messages while others are alert messages. When you download dataset from zenodo, you should see it

**Comment by Sun-HR02** [comment]
> > Hey, I have the same question. Could you give me a helping hand?
> 
> "-" indicates non-alert messages while others are alert messages. When you download dataset from zenodo, you should see it

Thank you. That really helps!
