### ISSUE TITLE
Label Files

### ISSUE THREAD

**Issue by yinyumeng** [logpai/loghub#4]
Hi, 

Thanks for sharing the log files! However, I didn't find the anomaly_labels for datasets in the repo, could you please share the link? 

I find the label for HDFS in following link but I cannot find other labels such as the label for BGL dataset.
https://github.com/logpai/loghub/tree/bba4876fb9e45c78501e598950bf5ff68dfef7bf/HDFS

Thank you very much for kindly help!

Sincerely

**Comment by jimzhu** [comment]
The files in the repo are just 2k sample logs. Pls request the raw logs and label files from Zenodo link.

**Comment by yinyumeng** [comment]
Hi,

Thanks for the quick reply. I have applied for the data from the Zenodo. I didn't manage to find the label from BGL_tar.gz Would you mind helping to check where I can find the label for the dataset BGL? Thanks for kindly help!

Sincerely

**Comment by jimzhu** [comment]
Pls check the readme info here: https://github.com/logpai/loghub/blob/master/BGL/README.md . **In the first column of the log, "-" indicates non-alert messages while others are alert messages. **

**Comment by yinyumeng** [comment]
Hi @jimzhu , thank you very much for the clarification!
