### ISSUE TITLE
Hadoop log

### ISSUE THREAD

**Issue by WMwzy** [logpai/loghub#46]
Hello!

In LogHub, Hadoop log dataset are divided into different application parts with different id and have labels very clearly for every type but in LogPub(logHub 2.0), you mixed them only in one file but i want to get just WORDCOUNT application part with the same file path format of that as in LogHub. Can you help me with that? 

Thank you very much!

**Comment by zhujiem** [comment]
Loghub 2.0 is only for log parsing evaluation. In case you need seperate log files, you can still access loghub 1.0
