### ISSUE TITLE
Encoding issue with Linux log

### ISSUE THREAD

**Issue by asrmnw** [logpai/loghub#50]
Not sure whether it's an issue from here. But when try to read the current Linux.log (zenodo,  md5:6d1802d7778126f21c001c6aa7b6b106) with python i got
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 20: invalid start byte
```

can you confirm that or is that something probably going wrong on my side?

**Comment by asrmnw** [comment]
my fault. never mind

**Comment by asrmnw** [comment]
Sorry for the back and forth. After recognizing my fault, there is still the UnicodeDecodeError. This time:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 4536: invalid start byte
```

This is one place i found when opening the original decompressed log file Linux.log with vim:
![image](https://github.com/logpai/loghub/assets/159132789/11465523-c092-4322-bdf6-82f00fc11826)

**Comment by zhujiem** [comment]
If you use raw logs from production, such errors are not uncommon. Please just skip such rows if they are not so many.
