### ISSUE TITLE
Android dataset from "Tools and Benchmarks for Automated Log Parsing"

### ISSUE THREAD

**Issue by AgrawalAmey** [logpai/loghub#6]
Hi,

I need to run a few experiments on the andorid dataset mentioned in the paper "Tools and Benchmarks for Automated Log Parsing". Would it be possible to share that dataset?

Thank you.

**Comment by jimzhu** [comment]
Please follow the link at README to request the raw datasets.

**Comment by AgrawalAmey** [comment]
I already requested and received access to the dataset. However, the dataset available of download is much smaller that the one described in the paper.

**Comment by jimzhu** [comment]
Yes, our paper uses the data in production. But the smaller data that we have released Android log have the same properties with the original one.
