### ISSUE TITLE
Feature (Column) Names of HDFS_1 and HDFS_2 Files

### ISSUE THREAD

**Issue by Mesv** [logpai/loghub#7]
Can you give me information about feature names of the files mentioned in the title? For example

081109 203518 143 INFO dfs.DataNode$DataXceiver: Receiving block blk_-1608999687919862906 src: /10.250.19.102:54106 dest: /10.250.19.102:50010

What does above row say?

**Comment by jimzhu** [comment]
HDFS format is: date, time, pid, level, component, content

**Comment by Mesv** [comment]
Do you mean for my question

081109     -> Date
203518    -> Time
143          -> pid
INFO        -> level

I am not sure about component and content. Can you make it clear?

**Comment by jimzhu** [comment]
The log format can be infered from HDFS source code. The content means the event and parameters recorded by developers. The component is the part of source code that generates the log message.
